### ISSUE TITLE
Deploy Cluster-Level Logging on Amazon EKS Cluster using Fluentd and Amazon CloudWatch Logs

### ISSUE THREAD

**Issue by jicowan** [awslabs/container-content-ideas-for-aws#30]
https://github.com/aws-samples/reinvent2018-dev303-code/blob/master/docs/lab2.md

**Comment by ckassen** [comment]
Deploying fluentd and sending logs to CloudWatch Logs is also covered in this workshop: https://github.com/aws-samples/reinvent2018-dev303-code/blob/master/docs/lab2.md
