### ISSUE TITLE
Best practices for running Spring Boot applications on ECS and EKS

### ISSUE THREAD

**Issue by jicowan** [awslabs/container-content-ideas-for-aws#44]
https://spring.io/guides/gs/spring-boot-docker/

**Comment by srijitm** [comment]
I actually started working on exactly this task. I have built up a set of spring boot apps that use zuul and eureka. Currently they all come up with docker-compose. I am working on documenting the steps and the design to migrate these applications to ECS. 

I'd be happy to collaborate with people who are interested.

Project: https://github.com/srijitm/spring-microservices
